// <auto-generated />
using System;
using BoardGameRentalApp.DataAccess.SqLite.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoardGameRentalApp.DataAccess.SqLite.Migrations
{
    [DbContext(typeof(SqLiteContext))]
    [Migration("20190330194452_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gr")
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("BoardGameRentalApp.Core.Entities.BoardGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Bail");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 3, 30, 19, 44, 52, 84, DateTimeKind.Utc).AddTicks(3336));

                    b.Property<string>("Name");

                    b.Property<float>("PricePerDay");

                    b.HasKey("Id");

                    b.ToTable("BoardGames");
                });

            modelBuilder.Entity("BoardGameRentalApp.Core.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactNumber");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 3, 30, 19, 44, 52, 87, DateTimeKind.Utc).AddTicks(7597));

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BoardGameRentalApp.Core.Entities.GameRental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BoardGameId");

                    b.Property<int>("ClientId");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 3, 30, 19, 44, 52, 87, DateTimeKind.Utc).AddTicks(7776));

                    b.Property<float>("PaymentAmount");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("BoardGameId");

                    b.HasIndex("ClientId");

                    b.ToTable("GameRentals");
                });

            modelBuilder.Entity("BoardGameRentalApp.Core.Entities.GameRental", b =>
                {
                    b.HasOne("BoardGameRentalApp.Core.Entities.BoardGame", "BoardGame")
                        .WithMany("GameRentals")
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BoardGameRentalApp.Core.Entities.Client", "Client")
                        .WithMany("GameRentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
