version: '3.4'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

  sqlserver.linux:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"

  clients.api:
    image: ${DOCKER_REGISTRY-}clientsapi
    build:
      context: .
      dockerfile: Services/Clients.Api/Dockerfile
    depends_on:
            - sqlserver.linux

  games.api:
    image: ${DOCKER_REGISTRY-}gamesapi
    build:
      context: .
      dockerfile: Services/Games.Api/Dockerfile
    depends_on:
            - sqlserver.linux

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  rentals.api:
    image: ${DOCKER_REGISTRY-}rentalsapi
    build:
      context: .
      dockerfile: Services/Rentals.Api/Dockerfile
    depends_on:
            - mongo
  web.mvc:
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: Web/Web.Mvc/Dockerfile

